repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6  # Use the version of ruff you want
    hooks:
      - id: ruff
        types_or: [python, pyi]
        args: [format]
      - id: ruff-format
        types_or: [python, pyi]
