# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres_db
    shm_size: 5096mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db-pg:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v2.12.1
    container_name: mlflow-server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - ./mlruns:/mlflow/artifacts
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/artifacts --host 0.0.0.0

  dashboard:
    build:
      context: .
      dockerfile: src/dashboard/Dockerfile
    container_name: dashboard
    environment:
      - CONFIG_FILE=config_service.yaml
    volumes:
      - ./src:/usr/src/app/src
      - ./config:/usr/src/app/config
    ports:
      - "8051:8051"

