# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres_db
    # set shared memory limit when using docker-compose
    shm_size: 5096mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db-pg:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
