# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres_db
    shm_size: 5096mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db-pg:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v2.22.0
    container_name: mlflow-server
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
    ports:
      - "5000:5000"
    command: >
      bash -c "pip install boto3 && pip install psycopg2-binary && mlflow server --backend-store-uri postgresql://admin:admin@db:5432/mlflowdb --default-artifact-root s3://bucket --host 0.0.0.0"

  dashboard:
    build:
      context: .
      dockerfile: src/dashboard/Dockerfile
    container_name: dashboard
    environment:
      - CONFIG_FILE=config_service.yaml
    volumes:
      - ./src:/usr/src/app/src
      - ./config:/usr/src/app/config
    ports:
      - "8050:8050"

  # MinIO server
  minio:
    container_name: minio
    image: minio/minio
    expose:
      - "9000"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 1s
      timeout: 10s
      retries: 5
    command: server /data --console-address ":9001"
  # Create a bucket named "bucket" if it doesn't exist
  minio-create-bucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      bash -c "
      mc alias set minio http://minio:9000 minio minio123 &&
      if ! mc ls minio/bucket; then
        mc mb minio/bucket
      else
        echo 'bucket already exists'
      fi
      "

