vae:
  device: cuda
  input_dim: 8160
  hidden_dim: 512  # 512 GOOD
  second_hidden_dim: 256  # 128 GOOD
  latent_dim: 24  # 24 GOOD
  batch_size: 2
  learning_rate: 1e-3 # 1e-3 GOOD
  epochs: 100

generator:
  number_of_samples: 10000
  min_space: -2.5
  max_space: 2.5

cnn:
  device: cuda
  input_dim: 1 # One Measurement per Input (with 8160 Channels)
  first_layer: 1020
  second_layer: 510
  third_layer: 205
  fourth_layer: 100
  fc_first_layer: 50
  max_pool: 2
  adaptive_pool: 1
  use_processed_measurements: False
  use_processed_synthetics: True

splitter:
  vae: { "1": 20, "2": 20, "3": 20, "4": 20, "5": 20, "6": 10 } # Distribution to split identified isotopes as a training/test dataset, 1 means NO ISOTOPES, JUST MEASUREMENT
  cnn_validation: { "1": 20, "2": 20, "3": 20, "4": 20, "5": 20, "6": 10 } # Distribution for Validation Dataset, 1 Means NO ISOTOPES, JUST MEASUREMENT
  max_isotopes_per_measurement: 6

peakfinder:
  tolerance: 0.60 # CONFIDANCE / TOLERANCE FOR PEAKS
  nuclide_intensity: 1 # INTENSITY OF THE ENERGY
  matching_ratio: 0.01 # MATCHED
  interpolate_energy: True # RESCALING X-AXIS (ENERGY-AXIS)
  prominence: 1 # PROBABLY 2000, AFTER Z-SCALING NEEDS 0.4~
  width: 7
  rel_height: 5
  wlen: 8
  nuclides: [
    "cs137",
    "co60",
    "i131",
    "tc99m",
    "ra226",
    "th232",
    "u238",
    "am241",
    "eu152",
    "eu154",
    "cs145"
  ]

measurements:
  number_of_channels: 8160
  step_size: 0.34507313512321336

postges_db:
  username: admin
  password: admin
  host: localhost
  port: 5432
  database: nuclide

mlflow:
  uri: http://localhost:5000

minio:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
  MLFLOW_S3_ENDPOINT_URL: http://localhost:9000

path:
  measurements: "data/measurements/"
  nuclides: "data/nuclides/"
  output: "data/"
